id: A3BC64A56
title: Supplication to Lord Buddha together with the Sixteen Arhats
type: translation
pechas:
- IBAB66458
- IE08D2EFE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:36:00.607082
  last_modified_at: 2023-01-04 12:36:00.607098
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IBAB66458/09A4: C5AD
  IE08D2EFE/F479: C5AD
